### ISSUE TITLE
Found no NVIDIA driver on your system - On Arch Linux

### ISSUE THREAD

**Issue by mdietrich16** [nixified-ai/flake#102]
Running the multi-user Nix daemon on Arch Linux but getting this error:
```Traceback (most recent call last):
  File "/nix/store/9mkwjz77d1cfa1xiwglmpy2wpv58yd7d-comfyui-unstable-2024-09-09/comfyui", line 90, in <module>
    import execution
  File "/nix/store/9mkwjz77d1cfa1xiwglmpy2wpv58yd7d-comfyui-unstable-2024-09-09/execution.py", line 13, in <module>
    import nodes
  File "/nix/store/9mkwjz77d1cfa1xiwglmpy2wpv58yd7d-comfyui-unstable-2024-09-09/nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "/nix/store/9mkwjz77d1cfa1xiwglmpy2wpv58yd7d-comfyui-unstable-2024-09-09/comfy/diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "/nix/store/9mkwjz77d1cfa1xiwglmpy2wpv58yd7d-comfyui-unstable-2024-09-09/comfy/sd.py", line 5, in <module>
    from comfy import model_management
  File "/nix/store/9mkwjz77d1cfa1xiwglmpy2wpv58yd7d-comfyui-unstable-2024-09-09/comfy/model_management.py", line 143, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "/nix/store/9mkwjz77d1cfa1xiwglmpy2wpv58yd7d-comfyui-unstable-2024-09-09/comfy/model_management.py", line 112, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/9s1hb2z6mffnswdar2bz3dl8bmblnq3p-python3-3.11.9-env/lib/python3.11/site-packages/torch/cuda/__init__.py", line 878, in current_device
    _lazy_init()
  File "/nix/store/9s1hb2z6mffnswdar2bz3dl8bmblnq3p-python3-3.11.9-env/lib/python3.11/site-packages/torch/cuda/__init__.py", line 314, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx
```
I am guessing this is also because of Nix/torch not finding `libcuda.so`, but I have no idea how to fix this. I have cuda 12.6, nvidia-open 560 driver installed and `nvidia-smi` works and shows the correct versions. I also tried `export LD_LIBRARY_PATH=/opt/cuda/targets/x86_64-linux/lib/stubs/` (which is where the `libcuda.so` from the Arch `cuda` package lives) before running `nix run`, no dice.

**Comment by MatthewCroughan** [comment]
Use NixOS or NixGL https://github.com/guibou/nixGL
