### ISSUE TITLE
Is Nvidia/CUDA passthru supposed to work on non NixOS Linux hosts?

### ISSUE THREAD

**Issue by mkoloberdin** [nixified-ai/flake#69]
I this a thing? The Readme mentions that it's supposed to work on WSL, but what about other Linux hosts? I am using Arch Linux.

Any pointers where to look to try to make it work or at least to figure out it it would work or not at all?

**Comment by MatthewCroughan** [comment]
It should, I mentioned in the video that things like invokeai work on a steam deck. But that was with AMD, can you please try and report back?

**Comment by mkoloberdin** [comment]
Textgen errors out while attempting to load a model. Unless I tick "cpu."
Here is the log:
```
2023-11-22 17:38:32 ERROR:Failed to load the model.
Traceback (most recent call last):
  File "/nix/store/1zzqmn5cl5c8dcbv37xp8xvvii892015-textgen-patchedSrc/modules/ui_model_menu.py", line 201, in load_model_wrapper
    shared.model, shared.tokenizer = load_model(shared.model_name, loader)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/1zzqmn5cl5c8dcbv37xp8xvvii892015-textgen-patchedSrc/modules/models.py", line 79, in load_model
    output = load_func_map[loader](model_name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/1zzqmn5cl5c8dcbv37xp8xvvii892015-textgen-patchedSrc/modules/models.py", line 141, in huggingface_loader
    model = model.cuda()
            ^^^^^^^^^^^^
  File "/nix/store/7hpffz24mjm12y5ymd2is43lxl7nf27b-python3-3.11.6-env/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2243, in cuda
    return super().cuda(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7hpffz24mjm12y5ymd2is43lxl7nf27b-python3-3.11.6-env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 905, in cuda
    return self._apply(lambda t: t.cuda(device))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/7hpffz24mjm12y5ymd2is43lxl7nf27b-python3-3.11.6-env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/nix/store/7hpffz24mjm12y5ymd2is43lxl7nf27b-python3-3.11.6-env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/nix/store/7hpffz24mjm12y5ymd2is43lxl7nf27b-python3-3.11.6-env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/nix/store/7hpffz24mjm12y5ymd2is43lxl7nf27b-python3-3.11.6-env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "/nix/store/7hpffz24mjm12y5ymd2is43lxl7nf27b-python3-3.11.6-env/lib/python3.11/site-packages/torch/nn/modules/module.py", line 905, in <lambda>
    return self._apply(lambda t: t.cuda(device))
                                 ^^^^^^^^^^^^^^
  File "/nix/store/7hpffz24mjm12y5ymd2is43lxl7nf27b-python3-3.11.6-env/lib/python3.11/site-packages/torch/cuda/__init__.py", line 247, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

```
The driver is installed on the host, `nvidia-smi` works fine.

**Comment by MatthewCroughan** [comment]
@mkoloberdin could you join the nixified.ai matrix chat to debug this further?

**Comment by 7omb** [comment]
I think I ran into the same issue, but did not find the reason yet. When the [hardware acceleration of llama-cpp-python](https://github.com/abetlen/llama-cpp-python#installation-with-hardware-acceleration) is activated with the cmake flags:

```
"-DLLAMA_CUBLAS=on"                
"-DCMAKE_CUDA_ARCHITECTURES=native"
```

the error:

```
CMake Error in vendor/llama.cpp/examples/llava/CMakeLists.txt:   
  CUDA_ARCHITECTURES is set to "native", but no GPU was detected.
```

is returned. I additionally added the cudatoolkit to the `buildInputs` as [described here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/by-name/ll/llama-cpp/package.nix#L26). You can ping me in matrix if you want to chat.

**Comment by mdietrich16** [comment]
Hey, having the same problem!
